name = "ApproximatingMapsBetweenLinearSpaces"
uuid = "31d768e5-ae28-4338-b319-fc9871ebca58"
authors = ["Simon Jacobsson <simon.jacobsson@kuleuven.be>"]
version = "0.1.1"

[deps]
ApproxFun = "28f2ccd6-bb30-5033-b560-165f7b14dc2f"
Flatten = "4c728ea3-d9ee-5c9a-9642-b6f7d7dc04fa"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SplitApplyCombine = "03a91e81-4c3e-53e1-a0a4-9c0c8f19dd66"
TensorToolbox = "9c690861-8ade-587a-897e-15364bc6f718"

[compat]
julia = "1"
ApproxFun = "0.13"
Flatten = "0.4"
IterTools = "1"
LinearAlgebra = "1"
SplitApplyCombine = "1"
TensorToolbox = "1"
